# config/packages/knpu_oauth2_client.yaml
#when@dev:
knpu_oauth2_client:
    http_client: guzzle
    clients:
        # the key "facebook_main" can be anything, it
        # will create a service: "knpu.oauth2.client.facebook_main"
        canvas_lms:
            type: canvas_lms
            canvas_instance_url: '%env(CANVASLMS_URL)%'
            client_id: '%env(OAUTH2_CANVASLMS_ID)%'
            client_secret: '%env(OAUTH2_CANVASLMS_SECRET)%'
            # the route that you're redirected to after
            # see the controller example below
            redirect_route: login_check
            redirect_params: {}
            use_state: true
            
